//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCtemplate1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        public string nim { get; set; }
        public string nama { get; set; }
        public Nullable<System.DateTime> tanggalLahir { get; set; }
        public string jenisKelamin { get; set; }
        public string alamat { get; set; }
    }
}
